### ISSUE TITLE
refactor UnitManager.UM() call in ListUnitsCTL

### ISSUE THREAD

**Issue by nickbaldwin** [ITC205/teamPurple#18]
UnitManager has a renamed method UM()  - now called getInstance()
Please refactor method call:

```
um = UnitManager.UM();
```

to:

```
um = UnitManager.getInstance();
```

**Comment by jkent13** [comment]
I changed where this was an issue for StudentUnitRecord (see referenced commit) and in cgCTL (see referenced commit for issue #19 - class is now called CheckGradeController). ListUnitsCTL isn't my class though... so no changes made there.

**Comment by nickbaldwin** [comment]
yeah... good point!
