### ISSUE TITLE
refactor UnitManager.UM() call in cgCTL

### ISSUE THREAD

**Issue by nickbaldwin** [ITC205/teamPurple#19]
UnitManager has a renamed method UM() - now called getInstance()
Please refactor method call:

```
IUnit u = UnitManager.UM().getUnit(cuc);
```

to: 

```
IUnit u = UnitManager.getInstance().getUnit(cuc);
```

**Comment by nickbaldwin** [comment]
Thought I'd track the work I'm doing... and the changes that will impact you guys. Hopefully it'll make things easier!

**Comment by jkent13** [comment]
Done
