### ISSUE TITLE
refactor Unit.getGrade() call in cgCTL

### ISSUE THREAD

**Issue by nickbaldwin** [ITC205/teamPurple#20]
Unit has a renamed method getGrade() - now called calculateGrade()
Please refactor method call:

```
String s = u.getGrade(f, g, h);
```

to:

```
String s = u.calculateGrade(f, g, h);
```

[note: the method this is in should also be renamed to calculateGrade]

**Comment by jkent13** [comment]
![image](https://cloud.githubusercontent.com/assets/12025558/9158568/62df8b28-3f5c-11e5-9d43-5da35fbda6bf.png)

Line 106
